package main

import (
"fmt"
"io/ioutil"
"log"
"net/http"
"regexp"
"strconv"
"strings"

"github.com/PuerkitoBio/goquery"
)

var client = &http.Client{}

func main() {

channels := []string{	
	"https://t.me/s/V2rayNGn",
	"https://t.me/s/DirectVPN",
	"https://t.me/s/ProxyFn",
	"https://t.me/s/NetAccount",
	"https://t.me/s/oneclickvpnkeysa",
	"https://t.me/s/daorzadannet",
	"https://t.me/s/Outline_Vpn",
	"https://t.me/s/vpn_xw",
	"https://t.me/s/prrofile_purple",
	"https://t.me/s/ShadowSocks_s",
	"https://t.me/s/azadi_az_inja_migzare",
	"https://t.me/s/WomanLifeFreedomVPN",
	"https://t.me/s/internet4iran",
	"https://t.me/s/LegenderY_Servers",
	"https://t.me/s/vpnfail_v2ray",
	"https://t.me/s/UnlimitedDev",
	"https://t.me/s/vmessorg",
	"https://t.me/s/v2rayNG_Matsuri",
	"https://t.me/s/vpn_ioss",
	"https://t.me/s/v2freevpn",
	"https://t.me/s/customv2ray",
	"https://t.me/s/FalconPolV2rayNG",
	"https://t.me/s/Jeyksatan",
	"https://t.me/s/hassan_saboorii",
	"https://t.me/s/v2rayvmess",
	"https://t.me/s/v2rayNGNeT",
	"https://t.me/s/server01012",
	"https://t.me/s/ShadowProxy66",
	"https://t.me/s/ipV2Ray",
	"https://t.me/s/kiava",
	"https://t.me/s/Helix_Servers",
	"https://t.me/s/PAINB0Y",
	"https://t.me/s/VpnProSec",
	"https://t.me/s/VlessConfig",
	"https://t.me/s/NIM_VPN_ir",
	"https://t.me/s/hashmakvpn",
	"https://t.me/s/X_Her0",
	"https://t.me/s/v2rayng_org",
	"https://t.me/s/v2rayngvpn",
	"https://t.me/s/custom_14",
	"https://t.me/s/v2rayNG_VPNN",
	"https://t.me/s/v2ray_outlineir",
	"https://t.me/s/v2_vmess",
	"https://t.me/s/FreeVlessVpn",
	"https://t.me/s/freeland8",
	"https://t.me/s/vmess_vless_v2rayng",
	"https://t.me/s/PrivateVPNs",
	"https://t.me/s/vmessiran",
	"https://t.me/s/vmessq",
	"https://t.me/s/WeePeeN",
	"https://t.me/s/V2rayNG3",
	"https://t.me/s/ShadowsocksM",
	"https://t.me/s/shadowsocksshop",
	"https://t.me/s/v2rayan",
	"https://t.me/s/VmessProtocol",
	"https://t.me/s/napsternetv_config",
	"https://t.me/s/Easy_Free_VPN",
	"https://t.me/s/V2Ray_FreedomIran",
	"https://t.me/s/V2RAY_VMESS_free",
	"https://t.me/s/v2ray_for_free",
	"https://t.me/s/V2rayN_Free",
	"https://t.me/s/free4allVPN",
	"https://t.me/s/vpn_ocean",
	"https://t.me/s/configV2rayForFree",
	"https://t.me/s/FreeV2rays",
	"https://t.me/s/DigiV2ray",
	"https://t.me/s/v2rayNG_VPN",
	"https://t.me/s/freev2rayssr",
	"https://t.me/s/v2rayn_server",
	"https://t.me/s/Shadowlinkserverr",
	"https://t.me/s/iranvpnet",
	"https://t.me/s/vmess_iran",
	"https://t.me/s/mahsaamoon1",
	"https://t.me/s/V2RAY_NEW",
	"https://t.me/s/v2RayChannel",
	"https://t.me/s/configV2rayNG",
	"https://t.me/s/config_v2ray",
	"https://t.me/s/vpnmasi",
	"https://t.me/s/v2ray_custom",
	"https://t.me/s/VPNCUSTOMIZE",
	"https://t.me/s/HTTPCustomLand",
	"https://t.me/s/vpn_proxy_custom",
	"https://t.me/s/ViPVpn_v2ray",
	"https://t.me/s/FreeNet1500",
	"https://t.me/s/v2ray_ar",
	"https://t.me/s/beta_v2ray",
	"https://t.me/s/vip_vpn_2022",
	"https://t.me/s/FOX_VPN66",
	"https://t.me/s/VorTexIRN",
	"https://t.me/s/YtTe3la",
	"https://t.me/s/V2RayOxygen",
	"https://t.me/s/Network_442",
	"https://t.me/s/VPN_443",
	"https://t.me/s/v2rayng_v",
	"https://t.me/s/ultrasurf_12",
	"https://t.me/s/proxy_bo",
	"https://t.me/s/narmafzarpc",
	"https://t.me/s/BugFreeNet",
	"https://t.me/s/vpn_luxury",
	"https://t.me/s/Glysit",
	"https://t.me/s/Avkeys",
	"https://t.me/s/OutlineVpnOfficial",	
	"https://t.me/s/",
	"https://t.me/s/academi_vpn",
	"https://t.me/s/ailumao",
	"https://t.me/s/alephproxy",
	"https://t.me/s/allofont",
	"https://t.me/s/alltelegramproxy",
	"https://t.me/s/aminsanayei",
	"https://t.me/s/amirtechno_service",
	"https://t.me/s/ammar_taraz",
	"https://t.me/s/amoozeshwebsite",
	"https://t.me/s/android_best",
	"https://t.me/s/angusmtp",
	"https://t.me/s/antifilterch",
	"https://t.me/s/antifilterjadid",
	"https://t.me/s/antifilterservice",
	"https://t.me/s/antimeli",
	"https://t.me/s/anty_filter",
	"https://t.me/s/apkgold",
	"https://t.me/s/ara_proxy",
	"https://t.me/s/architect_city",
	"https://t.me/s/armisstab",
	"https://t.me/s/armod_iran",
	"https://t.me/s/arz_proxy",
	"https://t.me/s/atlanticteamchannel",
	"https://t.me/s/atvpn",
	"https://t.me/s/avamaxiran",
	"https://t.me/s/awlix_ir",
	"https://t.me/s/azarbayjab1",
	"https://t.me/s/azphotoshop",
	"https://t.me/s/badupindao",
	"https://t.me/s/baipiao163",
	"https://t.me/s/baipiaowansui",
	"https://t.me/s/baipiaozero",
	"https://t.me/s/batproxy",
	"https://t.me/s/bax_proxy",
	"https://t.me/s/beiten",
	"https://t.me/s/beshkan",
	"https://t.me/s/beshkan_proxy",
	"https://t.me/s/billie_eilish_fp",
	"https://t.me/s/blackwacker",
	"https://t.me/s/bpjzx2",
	"https://t.me/s/bts_bngtn07",
	"https://t.me/s/build_apk",
	"https://t.me/s/canisproxy",
	"https://t.me/s/cengineer93",
	"https://t.me/s/chanel_config",
	"https://t.me/s/cheetah_mtp",
	"https://t.me/s/chrome_proxy",
	"https://t.me/s/cinemaa2areference",
	"https://t.me/s/click_vpnn",
	"https://t.me/s/clothdesign2023",
	"https://t.me/s/computer_it_engineering",
	"https://t.me/s/computerr_programming",
	"https://t.me/s/confing_problems",
	"https://t.me/s/cooperjon",
	"https://t.me/s/custominjector",
	"https://t.me/s/daneshjou_news",
	"https://t.me/s/darktunnelvip1",
	"https://t.me/s/daryaye_sorkhh",
	"https://t.me/s/dastorattermux",
	"https://t.me/s/data_proxy",
	"https://t.me/s/denait",
	"https://t.me/s/diana_subliminal1",
	"https://t.me/s/dipia_channel",
	"https://t.me/s/divar_daneshjoyi",
	"https://t.me/s/dr_proxyy",
	"https://t.me/s/drlinuxproxy",
	"https://t.me/s/durov_proxy",
	"https://t.me/s/editby",
	"https://t.me/s/editorprs1",
	"https://t.me/s/eiiim",
	"https://t.me/s/emergencyproxi",
	"https://t.me/s/esmart_vpn",
	"https://t.me/s/farsiiproxy",
	"https://t.me/s/fast_proxy",
	"https://t.me/s/fastnetir",
	"https://t.me/s/ferifox_proxy",
	"https://t.me/s/filmup_channel",
	"https://t.me/s/filtereshekan",
	"https://t.me/s/filtershekan_channel",
	"https://t.me/s/filterzapata",
	"https://t.me/s/fire_proxy_ir",
	"https://t.me/s/fix_proxy",
	"https://t.me/s/flash_proxies",
	"https://t.me/s/fnet00",
	"https://t.me/s/fonteditby",
	"https://t.me/s/foxnim",
	"https://t.me/s/free_proxy_com",
	"https://t.me/s/freeiranweb",
	"https://t.me/s/freenetpro99",
	"https://t.me/s/freeproxymaker",
	"https://t.me/s/freevpnchina",
	"https://t.me/s/g_v_h",
	"https://t.me/s/gangvpnir",
	"https://t.me/s/get_mtproto",
	"https://t.me/s/glypex",
	"https://t.me/s/goldproxy_meli",
	"https://t.me/s/goodomensworld",
	"https://t.me/s/graphicl",
	"https://t.me/s/graphicr",
	"https://t.me/s/graphicu",
	"https://t.me/s/hack_031_2022",
	"https://t.me/s/havraz_z",
	"https://t.me/s/hedcode",
	"https://t.me/s/helanet",
	"https://t.me/s/helga_v2ray",
	"https://t.me/s/hi_proxi",
	"https://t.me/s/hideproxi",
	"https://t.me/s/hl_proxy",
	"https://t.me/s/hoot_proxy",
	"https://t.me/s/hopevpn",
	"https://t.me/s/hotspotproxy",
	"https://t.me/s/huiguo62",
	"https://t.me/s/i_font",
	"https://t.me/s/icdl100",
	"https://t.me/s/icyber_one",
	"https://t.me/s/igraphical",
	"https://t.me/s/imtproto",
	"https://t.me/s/internalfeeling",
	"https://t.me/s/internet_nor",
	"https://t.me/s/ip_cf",
	"https://t.me/s/iphone02016vpn",
	"https://t.me/s/iproxify",
	"https://t.me/s/ipschannel",
	"https://t.me/s/iran_proxi",
	"https://t.me/s/iran_proxy7",
	"https://t.me/s/iran_v2ray1",
	"https://t.me/s/iranproxy",
	"https://t.me/s/iranvipproxy",
	"https://t.me/s/irn_vpn",
	"https://t.me/s/iroproxy",
	"https://t.me/s/isexologi",
	"https://t.me/s/ivaproxy",
	"https://t.me/s/iweb_developers",
	"https://t.me/s/jackalproxy",
	"https://t.me/s/jaxproxy",
	"https://t.me/s/jetmtp",
	"https://t.me/s/jiedianf",
	"https://t.me/s/jiedianssr",
	"https://t.me/s/jiujied",
	"https://t.me/s/job_freelancer",
	"https://t.me/s/jokerv2ray_guide",
	"https://t.me/s/jordanproxy",
	"https://t.me/s/kejixm123",
	"https://t.me/s/kingmtp",
	"https://t.me/s/kingporoxy",
	"https://t.me/s/kpopclub",
	"https://t.me/s/landporoxy",
	"https://t.me/s/lantern_proxy",
	"https://t.me/s/lanternproxies",
	"https://t.me/s/latincelebrities",
	"https://t.me/s/lemec_konkori",
	"https://t.me/s/lion_mtproto",
	"https://t.me/s/load_proxy",
	"https://t.me/s/loadproxy",
	"https://t.me/s/lock_proxy",
	"https://t.me/s/lora_proxy0",
	"https://t.me/s/lord_ul4mo",
	"https://t.me/s/lrn_proxifarabi",
	"https://t.me/s/ltscxk",
	"https://t.me/s/lyricsone",
	"https://t.me/s/machinegunkellyfp",
	"https://t.me/s/megavpn23",
	"https://t.me/s/mehrosaboran",
	"https://t.me/s/melli_config",
	"https://t.me/s/mester_modd",
	"https://t.me/s/mfjdpd",
	"https://t.me/s/midraem",
	"https://t.me/s/mister_styles",
	"https://t.me/s/mobile_33",
	"https://t.me/s/modirshabake",
	"https://t.me/s/moein_insta",
	"https://t.me/s/mov2ray",
	"https://t.me/s/mprxy",
	"https://t.me/s/mrkhalaq",
	"https://t.me/s/msamricana",
	"https://t.me/s/mt_proxi",
	"https://t.me/s/mt_proxy",
	"https://t.me/s/mt_proxyis",
	"https://t.me/s/mtp_poxy",
	"https://t.me/s/mtp_roto",
	"https://t.me/s/mtpproxyirani",
	"https://t.me/s/mtprot",
	"https://t.me/s/mtproto_dx",
	"https://t.me/s/mtproto_ir",
	"https://t.me/s/mtprotopr0xies",
	"https://t.me/s/mtproxymeli",
	"https://t.me/s/mtproxymeliorg",
	"https://t.me/s/mtproxynew3",
	"https://t.me/s/mtproxystar",
	"https://t.me/s/musiclyricsir",
	"https://t.me/s/my_universez",
	"https://t.me/s/myporoxy",
	"https://t.me/s/mysecure1",
	"https://t.me/s/nahad_channel",
	"https://t.me/s/napsternetvirani",
	"https://t.me/s/negar_psdha",
	"https://t.me/s/negarpsd",
	"https://t.me/s/network_zone",
	"https://t.me/s/networkerit",
	"https://t.me/s/nextgenproxy",
	"https://t.me/s/nodirani",
	"https://t.me/s/nordproxi",
	"https://t.me/s/noteproxy",
	"https://t.me/s/novln_proxy",
	"https://t.me/s/nproxy",
	"https://t.me/s/old_proxy",
	"https://t.me/s/onedtwitter",
	"https://t.me/s/onedworlds",
	"https://t.me/s/opera_proxy",
	"https://t.me/s/oxnet_ir",
	"https://t.me/s/parsaproxy",
	"https://t.me/s/parsashonam",
	"https://t.me/s/pc_it_mob",
	"https://t.me/s/pcandmob",
	"https://t.me/s/peakvpn",
	"https://t.me/s/persianproxy_official",
	"https://t.me/s/piavpn_account_free",
	"https://t.me/s/pinkproxy",
	"https://t.me/s/pintrest_photos",
	"https://t.me/s/plusmtproto",
	"https://t.me/s/pmcproxy",
	"https://t.me/s/polproxy",
	"https://t.me/s/poroximel",
	"https://t.me/s/poroxyjet",
	"https://t.me/s/positionn",
	"https://t.me/s/powerfulproxy",
	"https://t.me/s/pro0oxyi",
	"https://t.me/s/pro0xiy",
	"https://t.me/s/programming0to100",
	"https://t.me/s/proxi_fun",
	"https://t.me/s/proxicoom",
	"https://t.me/s/proxie",
	"https://t.me/s/proxies_whatsapp_new",
	"https://t.me/s/proxiesgram",
	"https://t.me/s/proxiesland",
	"https://t.me/s/proxiesstelegram",
	"https://t.me/s/proxifather",
	"https://t.me/s/proxistarlink",
	"https://t.me/s/proxiteiegram",
	"https://t.me/s/proxse11",
	"https://t.me/s/proxsiarshad",
	"https://t.me/s/proxxy_tweet",
	"https://t.me/s/proxxydaily",
	"https://t.me/s/proxy_360",
	"https://t.me/s/proxy_active",
	"https://t.me/s/proxy_amazon",
	"https://t.me/s/proxy_beta",
	"https://t.me/s/proxy_cartel",
	"https://t.me/s/proxy_cheap",
	"https://t.me/s/proxy_connection",
	"https://t.me/s/proxy_daemi",
	"https://t.me/s/proxy_fier",
	"https://t.me/s/proxy_freel",
	"https://t.me/s/proxy_fs",
	"https://t.me/s/proxy_ghavy",
	"https://t.me/s/proxy_ghavyx",
	"https://t.me/s/proxy_iran88",
	"https://t.me/s/proxy_irano_0",
	"https://t.me/s/proxy_iranvpn",
	"https://t.me/s/proxy_kafee",
	"https://t.me/s/proxy_lland",
	"https://t.me/s/proxy_mtm",
	"https://t.me/s/proxy_mtm_store",
	"https://t.me/s/proxy_mtprotoir",
	"https://t.me/s/proxy_nayaab",
	"https://t.me/s/proxy_news2",
	"https://t.me/s/proxy_online",
	"https://t.me/s/proxy_pj",
	"https://t.me/s/proxy_seven",
	"https://t.me/s/proxy_sp",
	"https://t.me/s/proxy_star",
	"https://t.me/s/proxy_tel",
	"https://t.me/s/proxy_x69",
	"https://t.me/s/proxycity_mtproto",
	"https://t.me/s/proxycu",
	"https://t.me/s/proxydaemi",
	"https://t.me/s/proxydarsi",
	"https://t.me/s/proxydotnet",
	"https://t.me/s/proxyforopeta",
	"https://t.me/s/proxygolld",
	"https://t.me/s/proxyhagh",
	"https://t.me/s/proxyhubs",
	"https://t.me/s/proxyhubt",
	"https://t.me/s/proxyinstagram",
	"https://t.me/s/proxyirancel",
	"https://t.me/s/proxyirtm",
	"https://t.me/s/proxylegram",
	"https://t.me/s/proxyme",
	"https://t.me/s/proxymelat",
	"https://t.me/s/proxymtproto",
	"https://t.me/s/proxymtproto_tel",
	"https://t.me/s/proxymtprotoj",
	"https://t.me/s/proxypico",
	"https://t.me/s/proxysarver",
	"https://t.me/s/proxysharecn",
	"https://t.me/s/proxystore11",
	"https://t.me/s/proxystore666",
	"https://t.me/s/proxyswitch",
	"https://t.me/s/proxyy",
	"https://t.me/s/proxyymeliii",
	"https://t.me/s/psd_gram",
	"https://t.me/s/psdlandchannel",
	"https://t.me/s/public504",
	"https://t.me/s/pyroproxy",
	"https://t.me/s/python_0to100",
	"https://t.me/s/pythonforever",
	"https://t.me/s/quickproto",
	"https://t.me/s/rahagfx",
	"https://t.me/s/rahapsd",
	"https://t.me/s/rahavector",
	"https://t.me/s/rahavfx",
	"https://t.me/s/red_proxy1",
	"https://t.me/s/repairms",
	"https://t.me/s/rezadehqan_ir",
	"https://t.me/s/rip_vpn",
	"https://t.me/s/russian_proxy",
	"https://t.me/s/safenetir",
	"https://t.me/s/safous_vpn",
	"https://t.me/s/saveproxy",
	"https://t.me/s/sayeproof",
	"https://t.me/s/secureproxies",
	"https://t.me/s/sezar_sec",
	"https://t.me/s/shabakehmag",
	"https://t.me/s/shadowproxychannel",
	"https://t.me/s/shakeproxy",
	"https://t.me/s/shervin_famous",
	"https://t.me/s/shutterpic",
	"https://t.me/s/silver_proxiii",
	"https://t.me/s/sipschannel",
	"https://t.me/s/software_computerr",
	"https://t.me/s/soheilmehrzadeganfan",
	"https://t.me/s/srcvpn",
	"https://t.me/s/stable_proxies",
	"https://t.me/s/sureproxy",
	"https://t.me/s/surfsharkfreevpn",
	"https://t.me/s/t4jorg1",
	"https://t.me/s/tamirpc_net",
	"https://t.me/s/tarah_show",
	"https://t.me/s/tarrahimemari",
	"https://t.me/s/tavaanatech",
	"https://t.me/s/tc_android",
	"https://t.me/s/techcenter0",
	"https://t.me/s/techshieldco",
	"https://t.me/s/tehran30nema",
	"https://t.me/s/telmtproto",
	"https://t.me/s/tgmtproto",
	"https://t.me/s/tgunblock",
	"https://t.me/s/tgvpn6",
	"https://t.me/s/tm_bax_v2ray",
	"https://t.me/s/tmepprrrrooo",
	"https://t.me/s/tvvmood",
	"https://t.me/s/tweeterii",
	"https://t.me/s/unii_kar",
	"https://t.me/s/unique_proxy",
	"https://t.me/s/unlockproxy",
	"https://t.me/s/update_proxy",
	"https://t.me/s/v2bit",
	"https://t.me/s/v2ray60",
	"https://t.me/s/v2ray_33",
	"https://t.me/s/v2ray_best_server",
	"https://t.me/s/v2ray_cartel",
	"https://t.me/s/v2ray_ng",
	"https://t.me/s/v2ray_phoenix",
	"https://t.me/s/v2ray_reality_new",
	"https://t.me/s/v2ray_swhil",
	"https://t.me/s/v2ray_vpnir",
	"https://t.me/s/v2rayalivpn",
	"https://t.me/s/v2raying",
	"https://t.me/s/v2rayir1",
	"https://t.me/s/v2rayland02",
	"https://t.me/s/v2rayng_account_free",
	"https://t.me/s/v2rayng_bit",
	"https://t.me/s/v2rayng_coonfig",
	"https://t.me/s/v2rayng_daily",
	"https://t.me/s/v2rayng_fast",
	"https://t.me/s/v2rayng_master",
	"https://t.me/s/v2rayng_shi",
	"https://t.me/s/v2rayngninja",
	"https://t.me/s/v2rayngrr13",
	"https://t.me/s/v2rayrg",
	"https://t.me/s/v2rayserver2023",
	"https://t.me/s/v2rayseven",
	"https://t.me/s/v2raytz",
	"https://t.me/s/v2rez",
	"https://t.me/s/v_2rayngvpn",
	"https://t.me/s/v_circle",
	"https://t.me/s/varid_ir",
	"https://t.me/s/vionashop_ir",
	"https://t.me/s/vippublic1",
	"https://t.me/s/vipvpniran1",
	"https://t.me/s/vistav2ray",
	"https://t.me/s/vmess_v2",
	"https://t.me/s/vmesskhodam",
	"https://t.me/s/voxel3ddvray",
	"https://t.me/s/voxel3dvray",
	"https://t.me/s/voxellearn",
	"https://t.me/s/voxelobjectrevit",
	"https://t.me/s/voxelpostpro",
	"https://t.me/s/vpn_live",
	"https://t.me/s/vpn_proxy66",
	"https://t.me/s/vpn_shield",
	"https://t.me/s/vpn_solve",
	"https://t.me/s/vpn_v2a",
	"https://t.me/s/vpnclop",
	"https://t.me/s/vpncostume",
	"https://t.me/s/vpnefy",
	"https://t.me/s/vpnhouse_official",
	"https://t.me/s/vpnkanfik",
	"https://t.me/s/vpnprojects",
	"https://t.me/s/vpnproxy66",
	"https://t.me/s/vpnraya",
	"https://t.me/s/vpnsal",
	"https://t.me/s/vpnsshocean",
	"https://t.me/s/vpnstable",
	"https://t.me/s/vpnv2raytop",
	"https://t.me/s/vpnx4",
	"https://t.me/s/vpnx6",
	"https://t.me/s/west2ray",
	"https://t.me/s/whale_chanel",
	"https://t.me/s/whale_s",
	"https://t.me/s/wiloproxy",
	"https://t.me/s/winiproxy",
	"https://t.me/s/worldcode",
	"https://t.me/s/worldcode_cpp",
	"https://t.me/s/wxgqlfx",
	"https://t.me/s/x_mtp",
	"https://t.me/s/x_proxy_vpn",
	"https://t.me/s/xthewayiseeitx",
	"https://t.me/s/xv2rayng",
	"https://t.me/s/yaney_01",
	"https://t.me/s/yekoyekvpn",
	"https://t.me/s/yellow_proxy",
	"https://t.me/s/zaynmalikupdatez",
	"https://t.me/s/zdyz2",
	"https://t.me/s/zedmodeon",
	"https://t.me/s/ziaam_mayne",
	"https://t.me/s/zyfxlnn",
	"https://t.me/s/aifenxiang2020",
	"https://t.me/s/airproxies",
	"https://t.me/s/alfred_config",
	"https://t.me/s/alienvpn402",
	"https://t.me/s/alo_v2rayng",
	"https://t.me/s/alpha_omega_vpn",
	"https://t.me/s/alphawebnews",
	"https://t.me/s/am_teammm",
	"https://t.me/s/amironetwork",
	"https://t.me/s/anix_v2ray",
	"https://t.me/s/antifilterchv2",
	"https://t.me/s/appxa",
	"https://t.me/s/argotaz",
	"https://t.me/s/artemis_vpn_free",
	"https://t.me/s/artemisvpn1",
	"https://t.me/s/arv2ray",
	"https://t.me/s/arzenow_1",
	"https://t.me/s/aspeedvpn",
	"https://t.me/s/atvpn2",
	"https://t.me/s/avash_v2rayngg",
	"https://t.me/s/azad_intrnet",
	"https://t.me/s/best_v2rayng_speed",
	"https://t.me/s/bestv2rang",
	"https://t.me/s/blackvpn_shop",
	"https://t.me/s/blue_diamond77",
	"https://t.me/s/bluevpn111",
	"https://t.me/s/bolbolvpn",
	"https://t.me/s/bored_vpn",
	"https://t.me/s/bright_vpn",
	"https://t.me/s/canguro_english",
	"https://t.me/s/capital_net",
	"https://t.me/s/capoit",
	"https://t.me/s/castom_v2ray",
	"https://t.me/s/cf_clean",
	"https://t.me/s/ch_v2rayng",
	"https://t.me/s/cloudcityy",
	"https://t.me/s/club_vpn9",
	"https://t.me/s/cnfg_v2ray",
	"https://t.me/s/config_alpha",
	"https://t.me/s/config_vip7",
	"https://t.me/s/configforvpn",
	"https://t.me/s/configforvpn01",
	"https://t.me/s/configino",
	"https://t.me/s/configpositivefree",
	"https://t.me/s/configshub",
	"https://t.me/s/confin0",
	"https://t.me/s/cov2ray",
	"https://t.me/s/cpuvpn",
	"https://t.me/s/crown_vpn_org",
	"https://t.me/s/customvpnserver",
	"https://t.me/s/daozhang6666",
	"https://t.me/s/darbazeh_vpn",
	"https://t.me/s/daredevill_404",
	"https://t.me/s/darkfiilter",
	"https://t.me/s/darkteam_vpn",
	"https://t.me/s/darkvpnpro",
	"https://t.me/s/deadhacker1",
	"https://t.me/s/deamnet",
	"https://t.me/s/dingyue_center",
	"https://t.me/s/divare_tel",
	"https://t.me/s/dribble7",
	"https://t.me/s/drvpn18",
	"https://t.me/s/eecloud_ltd",
	"https://t.me/s/evilbx",
	"https://t.me/s/exogamers",
	"https://t.me/s/filtershekanssh1",
	"https://t.me/s/flyv2ray",
	"https://t.me/s/foxnt",
	"https://t.me/s/freakconfig",
	"https://t.me/s/free1_vpn",
	"https://t.me/s/free_httpcustom",
	"https://t.me/s/free_proxy_001",
	"https://t.me/s/free_v2rayy",
	"https://t.me/s/free_v2rayyy",
	"https://t.me/s/freeconfigv2",
	"https://t.me/s/freedatazone1",
	"https://t.me/s/freedatazonev2ray",
	"https://t.me/s/freenet",
	"https://t.me/s/freev2rayi",
	"https://t.me/s/freev2raym",
	"https://t.me/s/frev2ray",
	"https://t.me/s/funix_shope",
	"https://t.me/s/funza",
	"https://t.me/s/gatchang_apk",
	"https://t.me/s/gekujd",
	"https://t.me/s/gh_v2rayng",
	"https://t.me/s/global_net_vpn",
	"https://t.me/s/god_config",
	"https://t.me/s/god_v2ray",
	"https://t.me/s/goldenvpn_v2rayy",
	"https://t.me/s/gp_proxy_vpn",
	"https://t.me/s/guard_vip",
	"https://t.me/s/haoshangle",
	"https://t.me/s/hatunnel_vpn",
	"https://t.me/s/hermanosvpn",
	"https://t.me/s/hkaa0",
	"https://t.me/s/hope_net",
	"https://t.me/s/hopev2ray",
	"https://t.me/s/hpv2rayng",
	"https://t.me/s/https_config_injector",
	"https://t.me/s/huohuaygf",
	"https://t.me/s/icv2ray",
	"https://t.me/s/idigitalz",
	"https://t.me/s/init1984",
	"https://t.me/s/ipv2rayng",
	"https://t.me/s/iran2vip",
	"https://t.me/s/iran_access",
	"https://t.me/s/iran_ray",
	"https://t.me/s/iranian_proxy_vpn",
	"https://t.me/s/iranonline_news",
	"https://t.me/s/isegaro",
	"https://t.me/s/iseqaro",
	"https://t.me/s/itv2ray",
	"https://t.me/s/jiedian_share",
	"https://t.me/s/jokerv2ray",
	"https://t.me/s/khoneproxy",
	"https://t.me/s/kilid_stor",
	"https://t.me/s/kinsta_service",
	"https://t.me/s/kurd_v2ray",
	"https://t.me/s/kurdistan_vpn_perfectt",
	"https://t.me/s/l_agvpn13",
	"https://t.me/s/lagvpn13",
	"https://t.me/s/learnexploit",
	"https://t.me/s/lentrn_vpn",
	"https://t.me/s/lightning6",
	"https://t.me/s/lightv2ray",
	"https://t.me/s/lion_channel_vpn",
	"https://t.me/s/loatvpn",
	"https://t.me/s/lockey_vpn",
	"https://t.me/s/lrnbymaa",
	"https://t.me/s/m_buy",
	"https://t.me/s/mahdish0p",
	"https://t.me/s/masco899",
	"https://t.me/s/masoud_vpn1",
	"https://t.me/s/maznet",
	"https://t.me/s/mdvpnsec",
	"https://t.me/s/mehradlearn",
	"https://t.me/s/meli_v2rayng",
	"https://t.me/s/mellii_vpn",
	"https://t.me/s/melov2ray",
	"https://t.me/s/mftizi",
	"https://t.me/s/mkking21",
	"https://t.me/s/modcity99",
	"https://t.me/s/moft_vpn",
	"https://t.me/s/molovpn",
	"https://t.me/s/mpmehi",
	"https://t.me/s/mrstudiosfa",
	"https://t.me/s/mrvpn1403",
	"https://t.me/s/mso_666_baz",
	"https://t.me/s/msv2flyng",
	"https://t.me/s/msv2ray",
	"https://t.me/s/msv2rayng",
	"https://t.me/s/msv2raynp",
	"https://t.me/s/mtconfig",
	"https://t.me/s/my_archive69",
	"https://t.me/s/my_dns_v2ray",
	"https://t.me/s/napsternetvapp",
	"https://t.me/s/napsternetvi",
	"https://t.me/s/netbox2",
	"https://t.me/s/new_mtproxi",
	"https://t.me/s/nitroserver_ir",
	"https://t.me/s/nodpai",
	"https://t.me/s/novinology",
	"https://t.me/s/nt_safe",
	"https://t.me/s/nufilter",
	"https://t.me/s/num1_shop",
	"https://t.me/s/nv_configs",
	"https://t.me/s/official_maxvpn",
	"https://t.me/s/oneclickn",
	"https://t.me/s/oneclickvpnkeys",
	"https://t.me/s/outline_ir",
	"https://t.me/s/outline_oneclick1",
	"https://t.me/s/outlinev2rayng",
	"https://t.me/s/outlinevpnir",
	"https://t.me/s/outlinevpnofficial",
	"https://t.me/s/ovpn2",
	"https://t.me/s/p_tech2024",
	"https://t.me/s/pinkpotatocloud",
	"https://t.me/s/pov2ray",
	"https://t.me/s/provpncip",
	"https://t.me/s/proxyfacts",
	"https://t.me/s/proxystore12",
	"https://t.me/s/qv2raychannel",
	"https://t.me/s/rayvps",
	"https://t.me/s/reality_daily",
	"https://t.me/s/retro_shop17",
	"https://t.me/s/revoltvpn",
	"https://t.me/s/riflvpn",
	"https://t.me/s/royalping_ir",
	"https://t.me/s/rxv2ray",
	"https://t.me/s/safenet_server",
	"https://t.me/s/saferoadnet",
	"https://t.me/s/sasan_web",
	"https://t.me/s/securit_y_breach",
	"https://t.me/s/server444",
	"https://t.me/s/server_vip_ir",
	"https://t.me/s/servermomo",
	"https://t.me/s/servernett",
	"https://t.me/s/shadowsocks_1",
	"https://t.me/s/sharecentrepro",
	"https://t.me/s/shh_proxy",
	"https://t.me/s/shopingv2ray",
	"https://t.me/s/shv2ray",
	"https://t.me/s/sin313",
	"https://t.me/s/sobi_vpn",
	"https://t.me/s/souqun8816",
	"https://t.me/s/souqun8817",
	"https://t.me/s/sstpvpn",
	"https://t.me/s/talentvpn",
	"https://t.me/s/tarahan_home",
	"https://t.me/s/tc_v2ray",
	"https://t.me/s/techno_v2rayvpn",
	"https://t.me/s/tehranargo",
	"https://t.me/s/thehotvpn",
	"https://t.me/s/therealaleph",
	"https://t.me/s/timingvpn",
	"https://t.me/s/titan_v2rayng",
	"https://t.me/s/titan_v2rayvpn",
	"https://t.me/s/tmnet_news",
	"https://t.me/s/tongtiange",
	"https://t.me/s/top_neti",
	"https://t.me/s/tpvpn_official",
	"https://t.me/s/tunder_vpn",
	"https://t.me/s/tunelvip",
	"https://t.me/s/unicornv2ray",
	"https://t.me/s/v2_r_ayng",
	"https://t.me/s/v2_team",
	"https://t.me/s/v2fast100",
	"https://t.me/s/v2fetch",
	"https://t.me/s/v2line",
	"https://t.me/s/v2logy",
	"https://t.me/s/v2parsin",
	"https://t.me/s/v2pedia",
	"https://t.me/s/v2range",
	"https://t.me/s/v2ray16",
	"https://t.me/s/v2ray1_ng",
	"https://t.me/s/v2ray96",
	"https://t.me/s/v2ray_alpha_vip",
	"https://t.me/s/v2ray_donya",
	"https://t.me/s/v2ray_fark",
	"https://t.me/s/v2ray_fd",
	"https://t.me/s/v2ray_he",
	"https://t.me/s/v2ray_iran88",
	"https://t.me/s/v2ray_ka",
	"https://t.me/s/v2ray_napster_vpn",
	"https://t.me/s/v2ray_nonoal",
	"https://t.me/s/v2ray_seven",
	"https://t.me/s/v2ray_vpn_ir",
	"https://t.me/s/v2ray_youtube",
	"https://t.me/s/v2rayang201",
	"https://t.me/s/v2rayargon",
	"https://t.me/s/v2rayarmy",
	"https://t.me/s/v2rayaz",
	"https://t.me/s/v2raybe",
	"https://t.me/s/v2raybest1",
	"https://t.me/s/v2raybx",
	"https://t.me/s/v2raycollectordonate",
	"https://t.me/s/v2rayfa",
	"https://t.me/s/v2rayfastone",
	"https://t.me/s/v2rayfr",
	"https://t.me/s/v2rayfree1",
	"https://t.me/s/v2rayfree_server",
	"https://t.me/s/v2rayfreo",
	"https://t.me/s/v2rayhp",
	"https://t.me/s/v2rayhubvip",
	"https://t.me/s/v2rayi_net",
	"https://t.me/s/v2rayng0051",
	"https://t.me/s/v2rayng12023",
	"https://t.me/s/v2rayng_25",
	"https://t.me/s/v2rayng_blue",
	"https://t.me/s/v2rayng_channel_vpn",
	"https://t.me/s/v2rayng_config_amin",
	"https://t.me/s/v2rayng_confiings",
	"https://t.me/s/v2rayng_confings",
	"https://t.me/s/v2rayng_galaxy",
	"https://t.me/s/v2rayng_im",
	"https://t.me/s/v2rayng_oorg",
	"https://t.me/s/v2rayng_outlinee",
	"https://t.me/s/v2rayng_ribvar",
	"https://t.me/s/v2rayng_serveer1",
	"https://t.me/s/v2rayng_vip",
	"https://t.me/s/v2rayng_vip7",
	"https://t.me/s/v2rayng_vpnrog",
	"https://t.me/s/v2rayngconfings",
	"https://t.me/s/v2rayngmat",
	"https://t.me/s/v2rayngn",
	"https://t.me/s/v2rayngprivate",
	"https://t.me/s/v2rayngte",
	"https://t.me/s/v2rayngup",
	"https://t.me/s/v2rayngupp",
	"https://t.me/s/v2rayngvp",
	"https://t.me/s/v2rayngvpni",
	"https://t.me/s/v2rayopen",
	"https://t.me/s/v2rayproxy",
	"https://t.me/s/v2rayroz",
	"https://t.me/s/v2raysfree",
	"https://t.me/s/v2rayshop_m",
	"https://t.me/s/v2raysiran",
	"https://t.me/s/v2rayturbo",
	"https://t.me/s/v2rayvpn2",
	"https://t.me/s/v2rayweb",
	"https://t.me/s/v2rayxd",
	"https://t.me/s/v2rayy_napsternetv",
	"https://t.me/s/v2rayyngvpn",
	"https://t.me/s/v2sparrow",
	"https://t.me/s/v_2r_ay",
	"https://t.me/s/vbox778",
	"https://t.me/s/vip_mod_chanel",
	"https://t.me/s/vipv2ra",
	"https://t.me/s/vless_vmess",
	"https://t.me/s/vmessx",
	"https://t.me/s/vp22ray",
	"https://t.me/s/vpn_amo",
	"https://t.me/s/vpn_kamyab",
	"https://t.me/s/vpn_kanfik",
	"https://t.me/s/vpn_mikey",
	"https://t.me/s/vpn_mikey5",
	"https://t.me/s/vpn_storm",
	"https://t.me/s/vpn_tehran",
	"https://t.me/s/vpn_ttrustt",
	"https://t.me/s/vpn_v24",
	"https://t.me/s/vpn_v2ra_ng",
	"https://t.me/s/vpn_v2ray_wireguard",
	"https://t.me/s/vpn_v2rayng_iran",
	"https://t.me/s/vpn_v2viip_channel",
	"https://t.me/s/vpncostumer",
	"https://t.me/s/vpnepic",
	"https://t.me/s/vpnfreesec",
	"https://t.me/s/vpnhub69",
	"https://t.me/s/vpnplus100",
	"https://t.me/s/vpnpopular2023",
	"https://t.me/s/vpns_ir",
	"https://t.me/s/vpnserverrr",
	"https://t.me/s/vpntwitt",
	"https://t.me/s/vpnv2speed",
	"https://t.me/s/vpnvg",
	"https://t.me/s/wancloudfa",
	"https://t.me/s/webshecan",
	"https://t.me/s/world_vmess",
	"https://t.me/s/wxdy666",
	"https://t.me/s/wxgmrjdcc",
	"https://t.me/s/xiv2ray",
	"https://t.me/s/xnxv2ray",
	"https://t.me/s/xrayproxy",
	"https://t.me/s/xrayzxn",
	"https://t.me/s/xsv2ray",
	"https://t.me/s/yunbaitech",
	"https://t.me/s/zayn_vpn",
	"https://t.me/s/zed_vpn",
	"https://t.me/s/zen_cloud",
	"https://t.me/s/zerobaipiao",
	"https://t.me/s/zibanabz",
	"https://t.me/s/zyfxlnn",
	"https://t.me/s/zzt2424",	
	"https://t.me/s/ip_cf",	}

output := ""

myregex := map[string]string{
"ss":     `(.{3})ss:\/\/`,
"vmess":  `vmess:\/\/`,
"trojan": `trojan:\/\/`,
"vless":  `vless:\/\/`,
"ssr":    `ssr:\/\/`,
"hy2":    `hy2:\/\/`,
"tuic":   `tuic:\/\/`,
}

for i := 0; i < len(channels); i++ {
all_messages := false
if strings.Contains(channels[i], "{all_messages}") {
all_messages = true
channels[i] = strings.Split(channels[i], "{all_messages}")[0]
}

req, err := http.NewRequest("GET", channels[i], nil)
if err != nil {
log.Fatalf("Error When requesting to: %d Error : %s", channels[i], err)
}

resp, err1 := client.Do(req)
if err1 != nil {
log.Fatal(err1)
}
defer resp.Body.Close()

doc, err := goquery.NewDocumentFromReader(resp.Body)
if err != nil {
log.Fatal(err)
}

messages := 10
link, exist := doc.Find(".tgme_widget_message_wrap .js-widget_message").Last().Attr("data-post")
if messages < 100 && exist == true {
number := strings.Split(link, "/")[1]
fmt.Println(number)

doc = GetMessages(100, doc, number, channels[i])
}

if all_messages {
fmt.Println(doc.Find(".js-widget_message_wrap").Length())
doc.Find(".tgme_widget_message_text").Each(func(j int, s *goquery.Selection) {
message_text := s.Text()
lines := strings.Split(message_text, "\n")
for a := 0; a < len(lines); a++ {
for _, regex_value := range myregex {
re := regexp.MustCompile(regex_value)
lines[a] = re.ReplaceAllStringFunc(lines[a], func(match string) string {
return "\n" + match
})
}
output += lines[a] + "\n"
}
})
} else {
doc.Find("code,pre").Each(func(j int, s *goquery.Selection) {
message_text := s.Text()
lines := strings.Split(message_text, "\n")
for a := 0; a < len(lines); a++ {
for proto_regex, regex_value := range myregex {
re := regexp.MustCompile(regex_value)
lines[a] = re.ReplaceAllStringFunc(lines[a], func(match string) string {
if proto_regex == "ss" {
if match[:3] == "vme" {
return "\n" + match
} else if match[:3] == "vle" {
return "\n" + match
} else if match[:3] == "ssr" {
return "\n" + match
} else {
return "\n" + match
}
} else {
return "\n" + match
}
})

if len(strings.Split(lines[a], "\n")) > 1 {
myconfigs := strings.Split(lines[a], "\n")
for i := 0; i < len(myconfigs); i++ {
if myconfigs[i] != "" {
re := regexp.MustCompile(regex_value)
myconfigs[i] = strings.ReplaceAll(myconfigs[i], " ", "")
match := re.FindStringSubmatch(myconfigs[i])
if len(match) >= 1 {
if proto_regex == "ss" {
if match[1][:3] == "vme" {
output += myconfigs[i] + "\n"
} else if match[1][:3] == "vle" {
output += myconfigs[i] + "\n"
} else if match[1][:3] == "ssr" {
output += myconfigs[i] + "\n"
} else {
output += myconfigs[i][3:] + "\n"
}
} else {
output += myconfigs[i] + "\n"
}
}
}
}
}
}
}
})
}
}

WriteToFile(output, "ready/fromtele.txt")
}

func WriteToFile(fileContent string, filePath string) {
err := ioutil.WriteFile(filePath, []byte(fileContent), 0644)
if err != nil {
fmt.Println("Error writing file:", err)
return
}

fmt.Println("File written successfully")
}

func load_more(link string) *goquery.Document {
req, _ := http.NewRequest("GET", link, nil)
fmt.Println(link)
resp, _ := client.Do(req)
doc, _ := goquery.NewDocumentFromReader(resp.Body)
return doc
}

func GetMessages(length int, doc *goquery.Document, number string, channel string) *goquery.Document {
x := load_more(channel + "?before=" + number)

html2, _ := x.Html()
reader2 := strings.NewReader(html2)
doc2, _ := goquery.NewDocumentFromReader(reader2)

// _, exist := doc.Find(".js-messages_more").Attr("href")
doc.Find("body").AppendSelection(doc2.Find("body").Children())

newDoc := goquery.NewDocumentFromNode(doc.Selection.Nodes[0])
// fmt.Println(newDoc.Find(".js-messages_more").Attr("href"))
messages := newDoc.Find(".js-widget_message_wrap").Length()

fmt.Println(messages)
if messages > length {
return newDoc
} else {
num, _ := strconv.Atoi(number)
n := num - 21
if n > 0 {
ns := strconv.Itoa(n)
GetMessages(length, newDoc, ns, channel)
} else {
return newDoc
}
}

return newDoc
}

func reverse(lines []string) []string {
for i := 0; i < len(lines)/2; i++ {
j := len(lines) - i - 1
lines[i], lines[j] = lines[j], lines[i]
}
return lines
}

func RemoveDuplicate(config string) string {
lines := strings.Split(config, "\n")

// Use a map to keep track of unique lines
uniqueLines := make(map[string]bool)

// Loop over lines and add unique lines to map
for _, line := range lines {
if len(line) > 0 {
uniqueLines[line] = true
}
}

// Join unique lines into a string
uniqueString := strings.Join(getKeys(uniqueLines), "\n")

return uniqueString
}

func getKeys(m map[string]bool) []string {
keys := make([]string, len(m))
i := 0
for k := range m {
keys[i] = k
i++
}
return keys
}