name: get

on:
  workflow_dispatch:
  schedule:
  - cron: "0 3 * * *"

  
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3.5.2

    - name: Install Python
      uses: actions/setup-python@v4.6.0
          
    - name: RunPython
      run: |
        pip install bs4 beautifulsoup4 requests
        python all.py
        

      
    - name: write
      run: |                 
        git config --global user.email "you@1.com"
        git config --global user.name "Your Name"
        git pull origin main
        git add -A
        git commit -m "Automatic update"
        git push


    - name: Telegram Message Notify
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.CHAT_ID_2 }}
        token: ${{ secrets.BOT_TOKEN }}
    
        message_file: SsL.txt
    
