name: sendss

on:
  workflow_dispatch:
  schedule:
  - cron: "0 3 * * *"
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3.5.2
  
    - name: te
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.CHAT_ID_4 }}
        token: ${{ secrets.BOT_TOKEN }}
        message: send photo message
        document: SsL.txt
    
