name: send

on:
  workflow_dispatch:
  schedule:
  - cron: "0 3 * * *"
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3.5.2
  
    - name: te
      uses: appleboy/telegram-action@v0.1.1
      with:
        to: ${{ secrets.CHAT_ID_2 }}
        token: ${{ secrets.BOT_TOKEN }}
        message_file: SsL.txt
    
